spring:
  oauth2:
    client:
      clientId: client1
      clientSecret: secret1
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      jwt:
        keyUri: http://localhost:8081/oauth/token_key
#      tokenInfoUri: http://localhost:8081/oauth/check_token
#      userInfoUri: http://localhost:8081/user
#      preferTokenInfo: true
#spring:
#  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false
zuul:
  routes:
    resource1:
      path: /resource1/**
      url: http://localhost:8082
      stripPrefix: true
      retryable: true